global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blockchain_nodes'
    static_configs:
      - targets: 
        - 'node1:3000'
        - 'node2:3000'
        - 'node3:3000'
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']